### ISSUE TITLE
Occasional error in log

### ISSUE THREAD

**Issue by SmallSansSerif** [CoderCow/Protector-Plugin#31] opened 2015-07-31 01:05 UTC
[Protector] Error One DoorUse event handler has thrown an unexpected exception. Exception details:
System.IndexOutOfRangeException: Array index is out of range.
  at Terraria.Plugins.Common.TerrariaTiles.get_Item (Point point) [0x00000] in <filename unknown>:0 
  at Terraria.Plugins.CoderCow.Protector.ProtectionManager+<EnumProtectionEntriesOnTopOfObject>d__1a.MoveNext () [0x00000] in <filename unknown>:0 
  at Terraria.Plugins.CoderCow.Protector.ProtectionManager+<EnumerateProtectionEntries>d__1.MoveNext () [0x00000] in <filename unknown>:0 
  at Terraria.Plugins.CoderCow.Protector.ProtectionManager.CheckBlockAccess (TShockAPI.TSPlayer player, Point tileLocation, Boolean fullAccessRequired, Terraria.Plugins.CoderCow.Protector.ProtectionEntry& relatedProtection) [0x00000] in <filename unknown>:0 
  at Terraria.Plugins.CoderCow.Protector.UserInteractionHandler.CheckProtected (TShockAPI.TSPlayer player, Point tileLocation, Boolean fullAccessRequired) [0x00000] in <filename unknown>:0 
  at Terraria.Plugins.CoderCow.Protector.UserInteractionHandler.HandleDoorUse (TShockAPI.TSPlayer player, Point location, Boolean isOpening, Direction direction) [0x00000] in <filename unknown>:0 
  at Terraria.Plugins.CoderCow.Protector.ProtectorPlugin.Net_DoorUse (System.Object sender, Terraria.Plugins.Common.Hooks.DoorUseEventArgs e) [0x00000] in <filename unknown>:0 
  at Terraria.Plugins.Common.Hooks.GetDataHookHandler.OnDoorUse (Terraria.Plugins.Common.Hooks.DoorUseEventArgs e) [0x00000] in <filename unknown>:0

**Comment by CoderCow** [comment] 2016-03-09 02:10
Can't reproduce. Might already have been fixed by older commits. Reopen if it still occurs.

**Closed by CoderCow** 2016-03-09 02:10 UTC
Labels: bug
